<?php

namespace cerveceriaBundle\Repository;

/**
 * tipoCervezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoCervezasRepository extends \Doctrine\ORM\EntityRepository
{
}
